// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/addMemberInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addMemberInfo').default>>>>
    }
    '/api/getMemberList': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getMemberList').default>>>>
    }
    '/api/getOneMemberInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getOneMemberInfo').default>>>>
    }
    '/member-management/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/member-management/members.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/member-management/members.post').default>>>>
    }
    '/member-management/members/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/member-management/members/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}